services:
  - type: web
    name: rotiseria_chatbot
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rotiseria_db
          property: connectionString
databases:
  - name: rotiseria-db
    plan: free
